name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run unit tests
      run: xcodebuild test -project NetPulse.xcodeproj -scheme NetPulse -destination 'platform=macOS'
